# -*- coding: utf-8 -*-
#
# Copyright (c) 2017 - 2018, doudoudzj
# All rights reserved.
#
# Intranet is distributed under the terms of the New BSD License.
# The full license can be found in 'LICENSE'.

"""Package for reading and writing Apache configuration.
"""

import glob
import os
import re
import shutil
import sys
from cStringIO import StringIO

import utils

DEBUG = False


HTTPD_CONF_DIR = '/etc/httpd/'
HTTPD_CONF = '/etc/httpd/conf/httpd.conf'
SERVER_CONF = '/etc/nginx/conf.d/'
COMMENTFLAG = '#v#'
GENBY = 'Generated by Intranet'


def change_document_root(self, root_path):
    '''设置站点路径'''

    if os.path.isdir(root_path):
        # 先备份
        shutil.copyfile(HTTPD_CONF + '.bak', HTTPD_CONF)
        conf = open(HTTPD_CONF).read()
        new_conf = re.sub('DocumentRoot "(.*?)"',
                          'DocumentRoot "' + root_path + '"',
                          conf)
        open(HTTPD_CONF, 'w').write(new_conf)
    else:
        return 'path_not_exist'


# https://blog.csdn.net/brucemj/article/details/37933519
# https://oomake.com/question/266681


vhost_start = re.compile(r'<VirtualHost\s+(.*?)>')
vhost_end = re.compile(r'</VirtualHost>')
docroot_re = re.compile(r'(DocumentRoot\s+)(\S+)')


def replace_docroot(conf_string, vhost, new_docroot):
    '''yield new lines of an httpd.conf file where docroot lines matching
        the specified vhost are replaced with the new_docroot
    '''
    conf_file = StringIO(conf_string)
    in_vhost = False
    curr_vhost = None
    for line in conf_file:
        vhost_start_match = vhost_start.search(line)
        if vhost_start_match:
            curr_vhost = vhost_start_match.groups()[0]
            in_vhost = True
        if in_vhost and (curr_vhost == vhost):
            docroot_match = docroot_re.search(line)
            if docroot_match:
                sub_line = docroot_re.sub(r'\1%s' % new_docroot, line)
                line = sub_line
            vhost_end_match = vhost_end.search(line)
            if vhost_end_match:
                in_vhost = False
            yield line


if __name__ == '__main__':
    import sys
    conf_file = sys.argv[1]
    vhost = sys.argv[2]
    docroot = sys.argv[3]
    conf_string = open(conf_file).read()
    for line in replace_docroot(conf_string, vhost, docroot):
        print line,
