#!/bin/sh
#
# Copyright (c) 2017, Jackson Dou
# All rights reserved.
#
# InPanel is distributed under the terms of the New BSD License.
# The full license can be found in 'LICENSE'.
#
# InPanel control script for Darwin.


# pick up any necessary environment variables
if test -f /usr/sbin/envvars; then
  . /usr/sbin/envvars
fi

# Source function library.
if [ -f /etc/rc.common ];then
   . /etc/rc.common
else
   echo 'not found file /etc/rc.common'
   exit
fi

LAUNCHCTL='/bin/launchctl'
# LAUNCHD_JOB='/System/Library/LaunchDaemons/org.inpanel.service.plist'
LAUNCHD_JOB='/Users/douzhenjiang/Library/LaunchAgents/org.inpanel.service.plist'

chmod 600 $LAUNCHD_JOB
chown root $LAUNCHD_JOB

run_launchctl() {
    if [ $(whoami) != 'root' ]; then
        echo "Must be root to run this script."
        exit 1
    fi
    $LAUNCHCTL $@
    # if [ -f LAUNCHD_JOB ];then
    #     $LAUNCHCTL $@
    # else
    #     echo "not found file $LAUNCHD_JOB"
    #     exit
    # fi
}

start_service() {
    run_launchctl load -w $LAUNCHD_JOB
    ERROR=$?
}

stop_service() {
    run_launchctl unload -w $LAUNCHD_JOB
    ERROR=$?
}

restart_service() {
    run_launchctl unload -w $LAUNCHD_JOB 2> /dev/null
    sleep 1
    start
    ERROR=$?
}

show_help() {
    echo 'Usage: inpanel {start|stop|restart|config|uninstall}'
    exit 2
}

if [ $# -lt 1 ]; then
    show_help
fi

case "$1" in
    start)
        start_service
        ;;
    stop)
        stop_service
        ;;
    restart)
        restart_service
        ;;
    config)
        . /usr/local/bin/inpanel-config
        if [ $# != 3 ]; then
            config_help
        else
            config_do $2 $3
        fi
        ;;
    uninstall)
        . /usr/local/bin/inpanel-uninstall
        uninstall_do $@
        ;;
    *)
        show_help
        ;;
esac
